config/routes.rb
Rails.application.routes.draw do
 
    resources :actus
    resources :apropos
    resources :contacts
    resources :publications

    	namespace :admin do
	  	resources :projets
	  	resources :users
      resources :publications

    end
 # 	resources :secteur
 # 	resources :pft
 #  resources :filiere

 	  namespace :super_admin do
      resources :publications
	    resources :users 
	    resources :projets
      resources :actus
      resources :tarifs
      resources :contacts
      resources :update_projets
  	end
    
   root to: 'home#index'
   devise_for :users, :controllers => { :sessions => "sessions" }
   get 'users/index'
   resources :projets
   get '/search' => 'projets#search', :as => 'search_projet'

   # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/projet.rb
class Projet < ApplicationRecord

        has_rich_text :body

        # validates :objectif_generale_du_projet, presence: true
        # validates :aspsp, presence: true

        has_one :update_projet
        
        belongs_to :bailleur, optional: true, class_name: 'User'
        belongs_to :ptf, optional: true
        belongs_to :appui, optional: true
        has_many :montants
# relation de table entre projet et secteur a travers benefprojet
        has_many :benefprojets
        has_many :beneficiaires, through: :benefprojets
   
# relation de table entre projet et secteur a travers zoneprojet
        has_many :zoneprojets
        has_many :zones, through: :zoneprojets
       
        # relation de table entre projet et secteur a travers igaprojets
        has_many :igaprojets
        has_many :igas, through: :igaprojets
      
     # relation de table entre projet et secteur a travers filiereprojets
        has_many :filiereprojets
        has_many :filieres, through: :filiereprojets
        

        # relation de table entre projet et secteur a travers secteurprojet

        has_many :secteurprojets 
        has_many :secteurs, through: :secteurprojets
    

        has_many :pemprojets
        has_many :pems, through: :pemprojets

        has_many :formeprojets
        has_many :formes, through: :formeprojets

        has_many :partenaireprojets
        has_many :partenaires, through: :partenaireprojets
    
        
        has_many_attached :files
        has_one_attached :picture
       

        # after_create :create_project_send
        # after_update :email_validation
        # after_update :email_rejet


        # This method calls the order_email method from user_mailer, passing the order as an argument
        # def create_project_send
        #     UserMailer.create_project_email(self).deliver_now
        # end

end

app/controllers/admin/projets_controller.rb
class Admin::ProjetsController < ApplicationController
    before_action :authenticate_user!
    # before_action :check_if_admin

    def index
      # if current_user.organisme
      #   if current_user.organisme.ptf != nil
      #     if current_user.organisme.ptf.title == "WBG"
      #       @projets = Projet.where(bailleur_id: current_user.id).order(id: :desc).page(params[:page]).per(9)
      #     else
      #       @projets = Projet.where(bailleur_id: current_user.id).order(id: :desc).page(params[:page]).per(9)
      #     end
      #   elsif current_user.organisme.nom != nil
      #       @projets = Projet.where(bailleur_id: current_user.id).order(id: :desc).page(params[:page]).per(9)
      #   elsif current_user.organisme.iga != nil
      #       @projets = Projet.where(bailleur_id: current_user.id).order(id: :desc).page(params[:page]).per(9)
      #   end
      # else
      #     @projets = Projet.where(bailleur_id: current_user.id).order(id: :desc).page(params[:page]).per(9)
      # end
      organisme = Organisme.where(user_id: current_user.id)[0]
      begin
        if organisme.ptf_id != nil
          @projets = Projet.where(bailleur_id: current_user.id).or(Projet.where(ptf_id: organisme.ptf_id)).order(id: :desc).page(params[:page]).per(9)
        elsif organisme.iga_id != nil
          @projets = Projet.joins(:igaprojets).where(igaprojets: { iga_id: organisme.iga_id }).or(Projet.where(bailleur_id: current_user.id)).order(id: :desc).page(params[:page]).per(9)
        else
          @projets = []
        end
      rescue
        @projets = []
      end

    end

    def new
      @project = Projet.new 
    end
    def create
              @project = Projet.create!(nom_du_projet: params[:nom_du_projet],
                ptf_id: params[:ptf],
                appui_id: params[:appui],
                objectif_generale_du_projet: params[:objectif_generale_du_projet],
                aspsp: params[:aspsp],comment: params[:comment],
                debut_du_projet: params[:debut_du_projet].to_date,
                fin: params[:fin].to_date, siteweb: params[:site],
                bailleur_id: current_user.id)

                if params[:creer] == 'Sauvegarder'
                    @project.update(validation: nil)
                    redirect_to admin_projets_path, success: "Votre fiche projet est sauvegardée. Vous pourrez reprendre votre travail ultérieurement et publier votre fiche lorsqu’elle sera complète"
                else
                    UserMailer.create_project_email(@project).deliver_now
                    redirect_to admin_projets_path, success: " Demande de création de fiche projet envoyée avec succès. Vous serez averti par email lorsqu'elle aura été validée et publiée par l'administrateur. Veuillez vérifier votre boîte « indésirables » ou « spam », le mail pourrait s’y trouver. "

                end

                for x in 1..Secteur.all.count
                  case params[:"unite_id#{x}"]
                    when "1"
                      @montant = params[:"montant#{x}"]
                      @convert_usd = @montant
                    when "2"
                      @montant = params[:"montant#{x}"]
                      @uac = Tarif.where(unite_id:  2, reference: "UAC").last.valeur
                      @convert_uac = @montant.to_i / @uac
                      @usd = Tarif.where(unite_id:  1, reference: "UAC").last.valeur
                      @convert_usd = @convert_uac * @usd
                    when "3"
                      @montant = params[:"montant#{x}"]
                      @convert_uac = @montant.to_i
                      @usd = Tarif.where(unite_id:  1, reference: "UAC").last.valeur
                      @convert_usd = @convert_uac * @usd

                    when "4"
                      @montant = params[:"montant#{x}"]
                      @uac = Tarif.where(unite_id:  4, reference: "UAC").last.valeur
                      @convert_uac = @montant.to_i / @uac
                      @usd = Tarif.where(unite_id:  1, reference: "UAC").last.valeur
                      @convert_usd = @convert_uac * @usd

                  end
                  if params[:"montant#{x}"].to_i > 0
                    Montant.create(price: @convert_usd.to_i,secteur_id: x, projet_id: @project.id, unite_id: 1)
                  end
                end
                  

                if params[:secteur_ids]   
                    @secteur_ids = params[:secteur_ids]
                  @secteur_ids.each do |x|
                    Secteurprojet.create(projet_id: @project.id , secteur_id: x.to_i)
                  end
                end
                
                  10.times do |x|
                  if params[:"checkfili#{x}"] && params[:newfili] != ""
                    @fili = Filiere.create(title: params[:"valfili#{x}"])
                      # SecteurFiliere.create(secteur_id: params[:secteur].to_i, filiere_id: @fili.id)
                      if params[:sectfil_ids]
                       @sectfil_ids = params[:sectfil_ids]
                        @sectfil_ids.each do |y|
                          SecteurFiliere.create(filiere_id: @fili.id , secteur_id: y.to_i)
                        end
                      end
                      Filiereprojet.create(projet_id: @project.id , filiere_id: @fili.id)
                  end
                end
                if params[:filiere_ids]
                  @filiere_ids = params[:filiere_ids]
                @filiere_ids.each do |x|
                  Filiereprojet.create(projet_id: @project.id , filiere_id: x.to_i)
                end
                end

                10.times do |x|
                  if params[:"checkform#{x}"] && params[:newform] != ""
                    @form = Forme.create(title: params[:"valform#{x}"])
                      if params[:sectform_ids]
                       @sectform_ids = params[:sectform_ids]
                          @sectform_ids.each do |y|
                            Formesecteur.create(forme_id: @form.id , secteur_id: y.to_i)
                          end
                      end
                      Formeprojet.create(projet_id: @project.id , forme_id: @form.id)
                  end
                end
                if params[:forme_ids]
                  @forme_ids = params[:forme_ids]
                @forme_ids.each do |x|
                  Formeprojet.create(projet_id: @project.id , forme_id: x.to_i)
                end
                end

                for x in 1..2
                  if params[:"partONG#{x}"]
                    @partenaire = Partenaire.create(plateforme: "ONG", description: params[:"desc_partONG#{x}"])
                    Partenaireprojet.create(projet_id: @project.id , partenaire_id: @partenaire.id)
                  end
                  if params[:"partASS#{x}"]
                    @partenaire = Partenaire.create(plateforme: "Associations", description: params[:"desc_partASS#{x}"])
                    Partenaireprojet.create(projet_id: @project.id , partenaire_id: @partenaire.id)
                  end

                  if params[:"partPRI#{x}"]
                    @partenaire = Partenaire.create(plateforme: "Secteurs Privés", description: params[:"desc_partPRI#{x}"])
                    Partenaireprojet.create(projet_id: @project.id , partenaire_id: @partenaire.id)
                  end

                  if params[:"partCOM#{x}"]
                    @partenaire = Partenaire.create(plateforme: "Chambres de Commerce", description: params[:"desc_partCOM#{x}"])
                    Partenaireprojet.create(projet_id: @project.id , partenaire_id: @partenaire.id)
                  end

                  if params[:"partAUTRE#{x}"]
                    @partenaire = Partenaire.create(plateforme: params[:"plat_partAUTRE#{x}"], description: params[:"desc_partAUTRE#{x}"])
                    Partenaireprojet.create(projet_id: @project.id , partenaire_id: @partenaire.id)
                  end

                end
                 

                10.times do |x|
                  if params[:"checkiga#{x}"] && params[:newiga] != ""
                    @iga = Iga.create(title: params[:"valiga#{x}"])
                    Igaprojet.create(projet_id: @project.id , iga_id: @iga.id)
                  end
                end 
                if params[:iga_ids] 
                  @iga_ids = params[:iga_ids]
                @iga_ids.each do |i|
                  Igaprojet.create(projet_id: @project.id , iga_id: i.to_i) 
                end
                end


                if params[:zone_ids]
                  @zone_ids = params[:zone_ids]
                @zone_ids.each do |z|
                  Zoneprojet.create(projet_id: @project.id , zone_id: z.to_i)
                end
                end

                10.times do |x|
                  if params[:"checkben#{x}"] && params[:newben] != ""
                    @ben = Beneficiaire.create(title: params[:"valben#{x}"])
                    Benefprojet.create(projet_id: @project.id , beneficiaire_id: @ben.id)
                  end
                end
                if params[:beneficiaire_ids]
                  @beneficiaire_ids = params[:beneficiaire_ids]
                @beneficiaire_ids.each do |b|
                  Benefprojet.create(projet_id: @project.id , beneficiaire_id: b.to_i)
                end
                end

                if params[:pem_ids]
                @pem_ids = params[:pem_ids]
                @pem_ids.each do |p|
                  Pemprojet.create(projet_id: @project.id , pem_id: p.to_i)
                end
                end

          if @project.save
            @project.files.attach(params[:files])
          else
            render :new

          end           
     end

  def show
    @projet = Projet.find(params[:id])
    @montant_total = 0
    if params[:creer] == 'Publier'
      @projet.update(validation: false)

    end
      @projet.montants.each do |m|

app/controllers/projets_controller.rb
class ProjetsController < ApplicationController
  
    def index
  
        if params[:search]
          if params[:search] == nil
              redirect_to(root_path)
          else  
            @parameter = params[:search].downcase  
            @res = Projet.where(validation: true) 
            @results = @res.where("lower(nom_du_projet) LIKE :search", search: "%#{@parameter}%")
          end  
      end

    end
  
    def show
      @projet = Projet.find(params[:id])
       @montant_total = 0
      respond_to do |format|
        format.html 
        format.pdf do
          render :pdf => "#{@projet.nom_du_projet}", :layout => '/layouts/pdf.html'
                
       end
      end

        @projet.montants.each do |m|
          @montant_total += m.price.to_i
        end
    end  
  end

app/helpers/super_admin/projets_helper.rb
module SuperAdmin::ProjetsHelper
end

app/views/projets/new.html.erb
  <header class="aci59a-0 eyAIuG haute sticky-limit">
    <div class="sc-1gnwgfb-2 stom">
    </div>
  </header>
<div class="mt-4 mb-4">
	<%= form_tag url_for(action: 'create'),method:'post', class:'form' do%>
		<div class="container">
			<div class="row mb-2">
				<div class="col-6">
					<div>
						<label for="nom" class="mr-2 tablePrint">Nom du projet </label>
					</div>
					<input type="text" name="nom_du_projet" id="nom" placeholder="Nom du projet" class="form-control">
				</div>
			</div>
			<div class="d-flex justify-content-between mb-3">
				<div>
					<h6 class="tablePrint">PTF</h6>
					<%= select_tag 'ptf_id', options_for_select(Ptf.all.collect{ |c| [c.title, c.id] }), :include_blank => "choisir", class: "form-control"%>
				</div>
				<div>
					<h6 class="tablePrint">Début</h6>
					<input type="date" name="debut_du_projet" class="form-control">
				</div>
				<div>
					<h6 class="tablePrint">Fin</h6>
					<input type="date" name="fin" class="form-control">
				</div>
				<div>
					<h6 class="tablePrint">Montant</h6>
					  <input name="montant" type = "range" min="0" max="60" onchange="rangevalue.value=value"/>
                  <output id="rangevalue">0</output> 
				</div>
				<div>
					<h6 class="tablePrint">Apui</h6>
					<%= select_tag 'appui_id', options_for_select(Appui.all.collect{ |c| [c.title, c.id] }), :include_blank => "choisir", class: "form-control"%>
				</div>
			</div>
		</div>

		<div class="container mb-2">
			<a class="btn-col" data-toggle="collapse" href="#secteur" role="button" aria-expanded="false" aria-controls="collapseExample">
				secteur
			</a>
				<div class="collapse" id="secteur">
				<div class="card card-body">
					<div class="row">
						<% Secteur.all.each do |c| %>
							<div class="col-12 col-md-6 col-xl-4">
								<%= check_box("secteur_id",c.id, {checked: false}, {class: "form-control"}) %>
								<%=h c.title%>
							</div> 
						<% end %>
					</div>
				</div>
				</div>
			</div>



			<div class="container mb-2">
			<a class="btn-col" data-toggle="collapse" href="#filiere" role="button" aria-expanded="false" aria-controls="collapseExample">
				Filiere
			</a>
				<div class="collapse" id="filiere">
				<div class="card card-body">
					<div class="row">
						<% Filiere.all.each do |c| %>
							<div class="col-md-3">
								<%= check_box("filiere_id",c.id, {checked: false}) %>
								<%=h c.title%>
							</div>
						<% end %>
					</div>
				</div>
				</div>
			</div>

			<div class="container mb-2">
				<a class="btn-col" data-toggle="collapse" href="#Beneficiaire" role="button" aria-expanded="false" aria-controls="collapseExample">
					Beneficiaire
				</a>
				<div class="collapse" id="Beneficiaire">
					<div class="card card-body">
						<div class="row">
							<% Beneficiaire.all.each do |c| %>
								<div class="col-md-4">
									<%= check_box("ben_id",c.id, {checked: false}) %>
									<%=h c.title%>
								</div>
							<% end %>
						</div>
					</div>
				</div>
			</div>
		<div class="container mb-2">
			<a class="btn-col" data-toggle="collapse" href="#iga" role="button" aria-expanded="false" aria-controls="collapseExample">
				IGA(institution gouvernemental associé)
			</a>
			<div class="collapse" id="iga">
				<div class="card card-body">
					<div class="row">
						<% Iga.all.each do |c| %>
							<div class="col-md-12">
								<%= check_box("iga_id",c.id, {checked: false}) %>
								<%=h c.title%>
							</div>
						<% end %>
					</div>
				</div>
			</div>
		</div>
		<div class="container mb-2">
			<a class="btn-col" data-toggle="collapse" href="#zi" role="button" aria-expanded="false" aria-controls="collapseExample">
				Région
			</a>
			<div class="collapse" id="zi">
				<div class="card card-body">
					<div class="row">
						<% Zone.all.each do |c| %>
							<div class="col-md-4">
								<%= check_box("zone_id",c.id, {checked: false}) %>
								<%=h c.title%>
							</div>
						<% end %>
					</div>
				</div>
			</div>
		</div>
		<div class="container mt-4">
			<input type="submit" value="Créer" class="sc-eerKOB cfnPHQ">
		</div>
	<% end %>
</div>

app/views/projets/show.html.erb
<header class="aci59a-0 eyAIuG sticky-limit">
    <div class="sc-1gnwgfb-2 hVIPFV picc position-relative">
      <style type="text/css">
        .picc{
          <%if @projet.secteurprojets.count == 1%>
            <%@projet.secteurprojets.each do|sp|%>
              <%if sp.secteur.title == "ENERGIE"%>
                background-image: url('/secteur/energie.jpg'); 
              <%else%>
                background-image: url('/<%=sp.secteur.image_url%>');
              <%end%>
            <%end%>
          <%else%>
            background-image: url('/secteur/accueil.jpg');
          <%end%>
        }
      </style>
      <div class="position-absolute entete">
        <h3 class="bg-fiche p-1 text-white"><%=@projet.nom_du_projet%></h3>
      </div>
    </div>
</header>
<div class="objectif mx-auto my-3 row align-items-start">
  <div class="col-12 col-md-2">
    <%if @projet.ptf.image_url%>
      <img src="/<%= @projet.ptf.image_url%>">
    <%end%>
  </div>
  <div class="ml-4 col-12 col-md-9 mt-2">
    <div>
      <div class="">
          <% if  @projet.secteurprojets.count > 0%>
            <%if  @projet.secteurprojets.count == 1%>
                <p><span class="attr">Secteur : </span>
            <%elsif @projet.secteurprojets.count > 1%>
                <p><span class="attr">Secteurs : </span>
            <%end%>
              <span class="word">
                <%@projet.secteurprojets .each do|sp|%>
                    <% if sp == @projet.secteurprojets.last%>
                      <%=sp.secteur.title %>
                    <% else %>
                      <%=sp.secteur.title %>, 
                    <% end %>
                <% end %>
              </span>
            </p>
          <%end%>
          
          <%if @projet.formeprojets.count > 0%>
            <% if @projet.formeprojets.count == 1%>
                <p><span class="attr">Forme d'appui : </span>
            <%elsif @projet.formeprojets.count > 1%>
                <p><span class="attr">Formes d'appui : </span>
            <%end%>
            <span class="word">
                <%@projet.formeprojets .each do|fop|%>
                  <% if fop == @projet.formeprojets.last%>
                    <%=fop.forme.title %>
                  <% else %>
                    <%=fop.forme.title %>, 
                  <% end %>
                <% end %>
              
            </span>
            </p>
          <%end%>

          <%if @projet.filiereprojets.count > 0%>
            <% if  @projet.filiereprojets.count == 1%>
                <p><span class="attr">Filière : </span>
            <%elsif @projet.filiereprojets.count > 1%>
                <p><span class="attr">Filières : </span>
            <%end%>
            <span class="word">
                <%@projet.filiereprojets .each do|fp|%>
                  <% if fp == @projet.filiereprojets.last%>
                    <%=fp.filiere.title %>
                  <% else %>
                    <%=fp.filiere.title %>, 
                  <% end %>
                <% end %>
            </span>
            </p>
          <%end%>
      </div>
    </div>
  </div>
</div>
  <div class="show-cont pt-4 pb-4">
    <div class="objectif mx-auto">
      <h2 class="text-left color">Objectif général du projet</h2>
      <div class="mt-2 ml-3 pt-2">
        <%= raw @projet.objectif_generale_du_projet%>
      </div>
      <div class="appui mt-4">
        <h2 class="color text-left">Appui spécifique au secteur privé</h2>
        <div class="mt-2 ml-3 p-2">
          <%= raw @projet.aspsp %>
        </div>
      </div>
      <div class="row pt-4 pb-4">
        <div class="col-md-6 list">


          <% if  @projet.igaprojets.count > 0%>
            <% if  @projet.igaprojets.count == 1%>
                <p><span class="attr">Institution Gouvernementale Associée : </span></p>
            <%elsif @projet.igaprojets.count > 1%>
                <p><span class="attr">Institutions Gouvernementales Associées : </span></p>
            <%end%>
            <div class="mb-3">
                <%@projet.igaprojets.each do|g|%>
                    <%if g == @projet.igaprojets.last%>
                      <span><%=g.iga.title %></span>
                    <% else %>
                      <span><%=g.iga.title %>, </span>
                    <% end %>
                <% end %>
            </div>
          <%end%>

          <% if  @projet.zoneprojets.count > 0%>
            <% if  @projet.zoneprojets.count == 1%>
                <p><span class="attr">Région : </span></p>
            <%elsif @projet.zoneprojets.count > 1%>
                <p><span class="attr">Régions : </span></p>
            <%end%>
            <div class="mb-3">
                <%@projet.zoneprojets .each do|zp|%>
                  <% if zp == @projet.zoneprojets.last%>
                    <%if zp.zone.id == 1%>
                      <span>National</span>
                    <%else%>
                      <span><%=zp.zone.title %></span>
                    <%end%>
                  <%else%>
                    <%if zp.zone.id == 1%>
                      <span>National, </span>
                    <%else%>
                      <span><%=zp.zone.title %>, </span>
                    <%end%>
                  <% end %>
                <% end %>
            </div>
          <%end%>
          
          <% if  @projet.partenaireprojets.count > 0%>
            <% if  @projet.partenaireprojets.count == 1%>
                <p><span class="attr">Partenaire d'implémentation : </span></p>
            <%elsif @projet.partenaireprojets.count > 1%>
                <p><span class="attr">Partenaires d'implémentations : </span></p>
            <%end%>
            <div class="mb-3">
                <%@projet.partenaireprojets .each do|pap|%>
                  <% if pap == @projet.partenaireprojets.last%>
                    <span><%=pap.partenaire.description %></span>
                  <%else%>
                    <span><%=pap.partenaire.description %>, </span>
                  <% end %>
                <% end %>
            </div>
          <%end%>


          <% if  @projet.benefprojets.count > 0%>
            <% if  @projet.benefprojets.count == 1%>
                <p><span class="attr">Bénéficiaire : </span></p>
            <%elsif @projet.benefprojets.count > 1%>
                <p><span class="attr">Bénéficiaires : </span></p>
            <%end%>
            <div class="mb-3">
                <%@projet.benefprojets .each do|ben|%>
                    <%if ben == @projet.benefprojets.last%>
                      <span><%=ben.beneficiaire.title %></span>
                    <% else %>
                      <span><%=ben.beneficiaire.title %>, </span>
                    <% end %>
                <% end %>
            </div>
          <%end%>

          <% if  @projet.secteurprojets.count > 0%>
          <%if  @projet.secteurprojets.count == 1%>
              <p><span class="attr">Montant  pour le secteur : </span>
          <%elsif @projet.secteurprojets.count > 1%>
              <p><span class="attr">Montant  pour les secteurs : </span>
          <%end%>
          </p>
          <div class="row">
            <% @projet.montants.each do |m|%>
                  <div class="col-12 col-md-7">
                    <span><%= m.secteur.title.titleize%> : </span>
                  </div>
                  <div class="col-12 col-md-5">
                    <span><%=  number_with_delimiter(m.price) %> <%= m.unite.nom%></span> 
                  </div>
            <%end%>
          </div>
          <%end%><br>
          <div class="row">
            <div class="col-12 col-md-7">
              <span class="attr">Montant total :</span>
            </div>
            <div class="col-12 col-md-5">
              <span><%= number_with_delimiter(@montant_total)%> USD</span> 
            </div>
          </div>
        </div>
        <div class="col-md-6 list">
          <p class="mb-3"><span class="attr">Nature de l'appui : </span><%=@projet.appui.title%></p>
          <%if @projet.debut_du_projet && @projet.fin%>
            <p class="mb-3"><span class="attr">Début de projet : </span><%=@projet.debut_du_projet.year%> &nbsp;&nbsp;&nbsp;&nbsp;
            <span class="attr">Fin de projet : </span><%=@projet.fin.year%></p>
          <%end%>
          <%if @projet.pemprojets.count >= 1%>
          <p><span class="attr">Alignement aux priorités du Plan Emergence Madagascar : </span></p>
            <div class="mb-3">
              <% @projet.pemprojets.each do |p|%>
                  <p><%=p.pem.title%></p>
              <%end%>
            </div>
          <%end%>
          
          <%if @projet.siteweb == " "%>
            <p class="mb-3"><span class="attr">Site web : </span>
                <span class="word">
                  <a href="https://<%= @projet.siteweb.remove('https://')%>"><%= @projet.siteweb%></a>
                </span>
            </p>
          <%end%>

          <%if @projet.files.attached?%>
            <p><span class="attr">Fichiers : </span>
            <%@projet.files.each do|file|%> 
              <%= link_to file.filename, rails_blob_path(file, disposition: "attachement") %></p>
            <%end%>
        <%end%>
       
        </div>
    </div>
    <div class="text-right">
      <%= link_to "Télécharger la fiche projet", projet_path(format: :pdf), :class => "sc-eerKOB cfnPHQ bold sear",  target: 'blank'%>
    </div>