config/routes.rb
Rails.application.routes.draw do
 
    resources :actus
    resources :apropos
    resources :contacts
    resources :publications

    	namespace :admin do
	  	resources :projets
	  	resources :users
      resources :publications

    end
 # 	resources :secteur
 # 	resources :pft
 #  resources :filiere

 	  namespace :super_admin do
      resources :publications
	    resources :users 
	    resources :projets
      resources :actus
      resources :tarifs
      resources :contacts
      resources :update_projets
  	end
    
   root to: 'home#index'
   devise_for :users, :controllers => { :sessions => "sessions" }
   get 'users/index'
   resources :projets
   get '/search' => 'projets#search', :as => 'search_projet'

   # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/publication.rb
class Publication < ApplicationRecord

	  has_many_attached :files
	  belongs_to :user
end

app/controllers/admin/publications_controller.rb
class Admin::PublicationsController < ApplicationController
	before_action :authenticate_user!
	def index
		@pubs = Publication.where(user_id: current_user.id).order(id: :desc).page(params[:page]).per(9)
	end
	def create
			@pub = Publication.create!(title: params[:title], description: params[:description], user_id: current_user.id)

	    	if @pub.save
	    		@pub.files.attach(params[:files])
	            redirect_to admin_publications_path, success: "Publication créée"
	        else
	            render :new

	        end  

	end
	def edit
		@pub = Publication.find(params[:id])
	end

	def update
	    @pub = Publication.find(params[:id])
	    if params[:files] != nil
		    if @pub.update(title: params[:title], description: params[:description],files: params[:files], user_id: current_user.id)
		       redirect_to admin_publication_path, success: "Modification terminée"
		   	end
		else
			if @pub.update(title: params[:title], description: params[:description], user_id: current_user.id)
		       redirect_to admin_publication_path, success: "Modification terminée"
		   	end
		end
	end
	
	def show
		@pub = Publication.find(params[:id])
	end

	def destroy
	  @pub = Publication.find(params[:id])
	  @pub.destroy
	  redirect_to admin_publications_path
	end
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_if_account_validate
  def index
  	@pubs = Publication.all.order(id: :desc).page(params[:page]).per(9)
  end

  def new

  end

  
  	
  def show
  	@pub = Publication.find(params[:id])
  end

  def update
  end

  private
  def check_if_account_validate
      if current_user.is_consultant == false && current_user.is_admin == nil && current_user.is_super_admin == false
        redirect_to root_path, success: "Compte en attente de validation, vous ne pouvez pas consulter toutes les publications"
      end
  end

end

app/controllers/super_admin/publications_controller.rb
class SuperAdmin::PublicationsController < ApplicationController
	before_action :authenticate_user!

	def create
	  	@pub = Publication.create!(title: params[:title], description: params[:description], user_id: current_user.id)

	    	if @pub.save
	    		@pub.files.attach(params[:files])
	            redirect_to super_admin_publications_path, success: "Publication créée avec succès"
	        else
	            render :new

	        end  
	end

	def edit
	   @pub = Publication.find(params[:id]) 	
	end 

	def update
		@pub = Publication.find(params[:id])

			if params[:files] != nil
		    	if @pub.update(title: params[:title], description: params[:description],files: params[:files],user_id: current_user.id)
		       		redirect_to super_admin_publication_path, success: "Modification terminéé"
			   	end
			else
				if @pub.update(title: params[:title], description: params[:description],user_id: current_user.id)
		       		redirect_to super_admin_publication_path, success: "Modification terminéé"
			   	end
		   	end

	end 

	def destroy
	  @pub = Publication.find(params[:id])
	  @pub.destroy
	  redirect_to super_admin_publications_path
		
	end

	def index
		@pubs = Publication.where(user_id: current_user.id).order(id: :desc).page(params[:page]).per(9)
	end
	
	def show
		@pub = Publication.find(params[:id])
	end
		
	
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/publications/index.html.erb
<div class="sans-head mb-5">
	<%if @pubs.count == 0 %>
			<div class="text-center text-muted mt-1 mb-4">
				<p> Aucune publication</p>
			</div>
		<%else%>
	<div class="mb-4 text-center">
		<h3 class="tablePrint">Toutes les publications</h3>
		</div>
	<div class="mx-auto row justify-content-center pub-width">
		<% @pubs.each do |a|%>
			<div class="col-10 col-md-3 card mx-1 mb-2 position-relative">
				<div class="card-body">
					 	 	<div class="card-title">
						    <h5 class="primary-color"><%= a.title %></h5>
						    </div>
						<div class="card-text">
							<p class="card-text text-muted mb-2 truncate-pub">
								<div class="mt-2 mb-5">
								<%= raw truncate(sanitize(a.description, tags: []), length: 100) %></p>
								</div>
						</div>
						<%if current_user.is_super_admin == false%>
						<p class="mt-3 position-absolute more-info-pub"><a href="<%= publication_path(a.id)%>" class="tablePrint">Voir</a></p>
						<%else%>
						<p class="mt-3 position-absolute more-info-pub"><a href="<%= admin_publication_path(a.id)%>" class="tablePrint">Voir</a></p>
						<%end%>
				</div>
			</div>
      <%end%>
	</div>
	<div class="text-center">
		<%= paginate @pubs %>
	</div>
<%end%>
</div>

app/views/publications/show.html.erb
<div class="container sans-head" >
	<div class="titre">
	<h5><%=@pub.title%></h5>
   </div>
   <div>
		<div class="mt-3">
			<p class="text-muted mt-3 mb-3 text-justify"><%= raw @pub.description%></p>
			<%if @pub.files.attached?%>
				<h5>Liste des documents associés :</h5>
				<ol class="ml-4">
					<%@pub.files.all.each do|file|%> 
						<li class="mb-3 mt-3"><%= link_to file.filename, rails_blob_path(file, disposition: "attachement"), class: "doc-relative ml-2 text-wrap text-break", target: :_blank%></li>
					<%end%>
				</ol>
			<%end%>
		</div>
	</div>
</div>