config/routes.rb
Rails.application.routes.draw do
 
    resources :actus
    resources :apropos
    resources :contacts
    resources :publications

    	namespace :admin do
	  	resources :projets
	  	resources :users
      resources :publications

    end
 # 	resources :secteur
 # 	resources :pft
 #  resources :filiere

 	  namespace :super_admin do
      resources :publications
	    resources :users 
	    resources :projets
      resources :actus
      resources :tarifs
      resources :contacts
      resources :update_projets
  	end
    
   root to: 'home#index'
   devise_for :users, :controllers => { :sessions => "sessions" }
   get 'users/index'
   resources :projets
   get '/search' => 'projets#search', :as => 'search_projet'

   # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/super_admin/actus_controller.rb
class SuperAdmin::ActusController < ApplicationController
  before_action :authenticate_user!

  def create
      @actu = Actu.create!(title: params[:title], date_publication: params[:date_publication], user_id: current_user.id)

      if @actu.save
       @actu.files.attach(params[:files])
       redirect_to new_super_admin_actu_path, success: "Actualité créée avec succès"
     else
       render :new

     end 


  end

  def new

    @actus = Actu.where(user_id: current_user.id).order(date_publication: :desc).page(params[:page]).per(9)
    @actu = Actu.new
  end

  def index
    @actus = Actu.where(user_id: current_user.id).order(date_publication: :desc).page(params[:page]).per(9)
  end

  def show
    @actu = Actu.find(params[:id])
  end

  def edit
    @actu = Actu.find(params[:id])
    @actus = Actu.where(user_id: current_user.id).order(date_publication: :desc).page(params[:page]).per(9)
  end

  def update
      @actu = Actu.find(params[:id])
      if params[:files] != nil
        if @actu.update(title: params[:title],files: params[:files], user_id: current_user.id)
         redirect_to super_admin_actu_path, succès: "Modification terminée"
        end
      else
        if @actu.update(title: params[:title], user_id: current_user.id)
         redirect_to super_admin_actu_path, succès: "Modification terminée"
        end
      end
  end

  def destroy
    @actu = Actu.find(params[:id])
    @actu.destroy
    redirect_to super_admin_actus_path
  end

end

app/controllers/super_admin/contacts_controller.rb
class SuperAdmin::ContactsController < ApplicationController
	before_action :authenticate_user!
  before_action :check_if_super_admin
  def index
    @messages = Message.all.order(created_at: :desc).page(params[:page]).per(10)
  end

  def show
  	@message = Message.find(params[:id])
  end

  def update
  	@message = Message.find(params[:id])
  	if paramsMessage == 'Marquer comme lu'
  		@message.update(read: true)
  	elsif paramsMessage == 'Marquer comme non lu'
  		@message.update(read: nil)
  	end
  	redirect_to super_admin_contacts_path
  end

def destroy
  @message = Message.find(params[:id])
  @message.destroy
  redirect_to super_admin_contacts_path
end

def check_if_super_admin
  if current_user.is_super_admin == false
    redirect_to root_path, success: "Vous n'êtes pas administrateur"
  end
  end



  private 
  def paramsMessage
  	params[:read]
  end
end

app/controllers/super_admin/projets_controller.rb
class SuperAdmin::ProjetsController < ApplicationController
    before_action :authenticate_user!
    before_action :check_if_super_admin
    # before_update :save


  def index
    @projets = Projet.where(validation: false, revalid: false).order(id: :desc).page(params[:page]).per(9)
    @projets_revalid = Projet.where(revalid: true, validation: false).order(id: :desc).page(params[:page]).per(9)
    @projets_valides = Projet.where(validation: true).order(id: :desc).page(params[:page]).per(9)
    @projets_rejets = Projet.where(rejet: true, validation: nil).order(id: :desc).page(params[:page]).per(9)
    @updateProjets = UpdateProjet.all.order(id: :desc).page(params[:page]).per(9)
  end

  def show
    @projet = Projet.find(params[:id])
    @montant_total = 0
      @projet.montants.each do |m|
        @montant_total += m.price.to_i
      end
  end

  def edit
    @projet = Projet.find(params[:id])
    @secteurprojets = Secteurprojet.where(projet_id: @projet.id)
    @sects = []
    @montants = []
    @secteurprojets.each do |sp|
      @sects << sp.secteur
      @sects.each do |s|
        @montants << s.montants
      end
    end
 

    @filiereprojets = Filiereprojet.where(projet_id: @projet.id)
    @fils = []
    @filiereprojets.each do |fp|
      @fils << fp.filiere
    end


    @formprojets = Formeprojet.where(projet_id: @projet.id)
    @forms = []
    @formprojets.each do |fop|
      @forms << fop.forme
    end

    @beneficiaireprojets = Benefprojet.where(projet_id: @projet.id)
    @bens = []
    @beneficiaireprojets.each do |bp|
      @bens << bp.beneficiaire
    end

    @igaprojets = Igaprojet.where(projet_id: @projet.id)
    @igas = []
    @igaprojets.each do |ip|
      @igas << ip.iga
    end

    @zoneprojets = Zoneprojet.where(projet_id: @projet.id)
    @zones = []
    @zoneprojets.each do |zp|
      @zones << zp.zone
    end

    @pemprojets = Pemprojet.where(projet_id: @projet.id)
    @pems = []
    @pemprojets.each do |ppro|
      @pems << ppro.pem
    end

  end

  def update
    @projet = Projet.find(params[:id])

    if rejetparam == 'Valider' || rejetparam == 'Revalider'
      @projet.update(validation: true, rejet: nil, revalid: false)
        UserMailer.email_validation(@projet).deliver_now
        redirect_to super_admin_projet_path, success: "Projet validé"
    elsif rejetparam == 'Rejeter'
      @projet.update(rejet: true, validation: nil, revalid: false)    
        UserMailer.email_rejet(@projet).deliver_now
        redirect_to super_admin_projet_path, success: "Projet rejeté"

    else
     
     if UpdateProjet.find_by(projet_id: @projet.id) == nil
        @projetmodif = UpdateProjet.create!(nom_du_projet: params[:nom_du_projet], 
       debut_du_projet: params[:debut_du_projet].to_date,
        objectif_generale_du_projet: params[:objectif_generale_du_projet],
       aspsp: params[:aspsp],fin: params[:fin].to_date, 
       appui_id: params[:appui], ptf_id: params[:ptf], projet_id: @projet.id)

        @projetmodif.secteurprojets.destroy_all
        @projetmodif.montants.destroy_all
      for x in 0..Secteur.all.count

        case params[:"unite_id#{x}"]
          when "1"
            @montant = params[:"montant#{x}"]
            @convert_usd = @montant
          when "2"
            @montant = params[:"montant#{x}"]
            @uac = Tarif.where(unite_id:  2, reference: "UAC").last.valeur
            @convert_uac = @montant.to_i / @uac
            @usd = Tarif.where(unite_id:  1, reference: "UAC").last.valeur
            @convert_usd = @convert_uac * @usd
          when "3"
            @montant = params[:"montant#{x}"]
            @convert_uac = @montant.to_i
            @usd = Tarif.where(unite_id:  1, reference: "UAC").last.valeur
            @convert_usd = @convert_uac * @usd

          when "4"
            @montant = params[:"montant#{x}"]
            @uac = Tarif.where(unite_id:  4, reference: "UAC").last.valeur
            @convert_uac = @montant.to_i / @uac
            @usd = Tarif.where(unite_id:  1, reference: "UAC").last.valeur
            @convert_usd = @convert_uac * @usd

        end
        if params[:"secteur_#{x}"]
          Secteurprojet.create(update_projet_id: @projetmodif.id, secteur_id: params[:"secteur_#{x}"])
          # Montant.create(price: params[:"montant#{params[:"secteur_#{x}"]}"],secteur_id: params[:"secteur_#{x}"], projet_id: @projet.id, unite_id: params[:"unite_id#{params[:"secteur_#{x}"]}"])
          Montant.create(price: @convert_usd.to_i,secteur_id: params[:"secteur_#{x}"], update_projet_id: @projetmodif.id, unite_id: 1)
        end
      end

      @projetmodif.filiereprojets.destroy_all
      10.times do |x|
        if params[:"checkfili#{x}"] && params[:newfili] != ""
          @fili = Filiere.create(title: params[:"valfili#{x}"])
          if params[:sectfil_ids]
          @sectfil_ids = params[:sectfil_ids]
          @sectfil_ids.each do |y|
            SecteurFiliere.create(filiere_id: @fili.id , secteur_id: y.to_i)
          end
          end
            Filiereprojet.create(update_projet_id: @projetmodif.id , filiere_id: @fili.id)
        end
      end
      if params[:filiere_ids]
        @filiere_ids = params[:filiere_ids]
        @filiere_ids.each do |x|
          Filiereprojet.create(update_projet_id: @projetmodif.id , filiere_id: x.to_i)
        end
      end

      @projetmodif.formeprojets.destroy_all
      10.times do |x|
        if params[:"checkform#{x}"] && params[:newform] != ""
          @form = Forme.create(title: params[:"valform#{x}"])
          if params[:sectform_ids]
           @sectform_ids = params[:sectform_ids]
          @sectform_ids.each do |y|
            Formesecteur.create(forme_id: @form.id , secteur_id: y.to_i)
          end
          end
            Formeprojet.create(update_projet_id: @projetmodif.id , forme_id: @form.id)
        end
      end
      if params[:forme_ids]
        params[:forme_ids].each do |forme_id|
          Formeprojet.create(update_projet_id: @projetmodif.id, forme_id: forme_id.to_i)
        end
      end

      @projetmodif.benefprojets.destroy_all
     10.times do |x|
        if params[:"checkben#{x}"] && params[:newben] != ""
          @ben = Beneficiaire.create(title: params[:"valben#{x}"])
          Benefprojet.create(update_projet_id: @projetmodif.id , beneficiaire_id: @ben.id)
        end
      end
      for x in 0..Beneficiaire.all.count-1
        if params[:"beneficiaire_#{x}"]
          Benefprojet.create(update_projet_id: @projetmodif.id, beneficiaire_id: params[:"beneficiaire_#{x}"])
        end
      end

      @projetmodif.igaprojets.destroy_all
      10.times do |x|
        if params[:"checkiga#{x}"] && params[:newiga] != ""
          @iga = Iga.create(title: params[:"valiga#{x}"])
          Igaprojet.create(update_projet_id: @projetmodif.id , iga_id: @iga.id)
        end
      end 
      for x in 0..Iga.all.count-1
        if params[:"iga_#{x}"]
          Igaprojet.create(update_projet_id: @projetmodif.id, iga_id: params[:"iga_#{x}"])
        end
      end


      @projetmodif.zoneprojets.destroy_all
      for x in 0..Zone.all.count-1
        if params[:"zone_#{x}"]
          Zoneprojet.create(update_projet_id: @projetmodif.id, zone_id: params[:"zone_#{x}"])
        end
      end

      @projetmodif.pemprojets.destroy_all
      for x in 0..Pem.all.count-1
        if params[:"pem_#{x}"]
          Pemprojet.create(update_projet_id: @projetmodif.id, pem_id: params[:"pem_#{x}"])
        end
      end
    

        redirect_to  super_admin_update_projets_path, success: "Modification terminée"

    elsif UpdateProjet.find_by(projet_id: @projet.id) != nil

        @projetmodif = UpdateProjet.where(projet_id: @projet.id)
        @projetmodif.update(nom_du_projet: params[:nom_du_projet], 
       debut_du_projet: params[:debut_du_projet].to_date,
        objectif_generale_du_projet: params[:objectif_generale_du_projet],
       aspsp: params[:aspsp],fin: params[:fin].to_date, 
       appui_id: params[:appui], ptf_id: params[:ptf], projet_id: @projet.id)


        @projetmodif.each do |p|
        p.secteurprojets.destroy_all
        p.montants.destroy_all
      for x in 0..Secteur.all.count

        case params[:"unite_id#{x}"]
          when "1"
            @montant = params[:"montant#{x}"]
            @convert_usd = @montant
          when "2"
            @montant = params[:"montant#{x}"]
            @uac = Tarif.where(unite_id:  2, reference: "UAC").last.valeur
            @convert_uac = @montant.to_i / @uac
            @usd = Tarif.where(unite_id:  1, reference: "UAC").last.valeur
            @convert_usd = @convert_uac * @usd
          when "3"
            @montant = params[:"montant#{x}"]
            @convert_uac = @montant.to_i
            @usd = Tarif.where(unite_id:  1, reference: "UAC").last.valeur
            @convert_usd = @convert_uac * @usd

          when "4"
            @montant = params[:"montant#{x}"]
            @uac = Tarif.where(unite_id:  4, reference: "UAC").last.valeur
            @convert_uac = @montant.to_i / @uac
            @usd = Tarif.where(unite_id:  1, reference: "UAC").last.valeur
            @convert_usd = @convert_uac * @usd

        end
        if params[:"secteur_#{x}"]
          Secteurprojet.create(update_projet_id: p.id, secteur_id: params[:"secteur_#{x}"])
          # Montant.create(price: params[:"montant#{params[:"secteur_#{x}"]}"],secteur_id: params[:"secteur_#{x}"], projet_id: @projet.id, unite_id: params[:"unite_id#{params[:"secteur_#{x}"]}"])
          Montant.create(price: @convert_usd.to_i,secteur_id: params[:"secteur_#{x}"], update_projet_id: p.id, unite_id: 1)
        end
      end

      p.filiereprojets.destroy_all
      10.times do |x|
        if params[:"checkfili#{x}"] && params[:newfili] != ""
          @fili = Filiere.create(title: params[:"valfili#{x}"])
          if params[:sectfil_ids]
           @sectfil_ids = params[:sectfil_ids]
          @sectfil_ids.each do |y|

app/controllers/super_admin/publications_controller.rb
class SuperAdmin::PublicationsController < ApplicationController
	before_action :authenticate_user!

	def create
	  	@pub = Publication.create!(title: params[:title], description: params[:description], user_id: current_user.id)

	    	if @pub.save
	    		@pub.files.attach(params[:files])
	            redirect_to super_admin_publications_path, success: "Publication créée avec succès"
	        else
	            render :new

	        end  
	end

	def edit
	   @pub = Publication.find(params[:id]) 	
	end 

	def update
		@pub = Publication.find(params[:id])

			if params[:files] != nil
		    	if @pub.update(title: params[:title], description: params[:description],files: params[:files],user_id: current_user.id)
		       		redirect_to super_admin_publication_path, success: "Modification terminéé"
			   	end
			else
				if @pub.update(title: params[:title], description: params[:description],user_id: current_user.id)
		       		redirect_to super_admin_publication_path, success: "Modification terminéé"
			   	end
		   	end

	end 

	def destroy
	  @pub = Publication.find(params[:id])
	  @pub.destroy
	  redirect_to super_admin_publications_path
		
	end

	def index
		@pubs = Publication.where(user_id: current_user.id).order(id: :desc).page(params[:page]).per(9)
	end
	
	def show
		@pub = Publication.find(params[:id])
	end
		
	
end

app/controllers/super_admin/tarifs_controller.rb
class SuperAdmin::TarifsController < ApplicationController
	before_action :authenticate_user!
  def index
    @tarifs = Tarif.all.order(id: :desc).page(params[:page]).per(9)
  end

  def edit
    @tarif = Tarif.find(params[:id])
    @tarifs = Tarif.all.order(id: :desc).page(params[:page]).per(9)
  end

  def update
      @tarif = Tarif.find(params[:id])
      if @tarif.update(reference: params[:reference], valeur: params[:valeur], unite_id: params[:unite])

        if params[:cree] == 'À utiliser'
          @tarif.update(utilise: true)

        end
        redirect_to edit_super_admin_tarif_path(@tarif.id), success: "Taux de change modifié!!"
      else
        render :new

      end  
  end

  # def new
  # 	@tarif = Tarif.new
  #   @tarifs = Tarif.all.order(id: :desc).page(params[:page]).per(9)
  # end

  # def create
	 #  	@tarif = Tarif.create!(reference: params[:reference], valeur: params[:valeur], unite_id: params[:unite])
  #       if params[:cree] == 'A utiliser'
  #         @tarif.update(utilise: true)

  #       end
		#   if @tarif.save
		#     redirect_to new_super_admin_tarif_path, success: "Taux de change créé!!"
		#   else
		#     render :new

		#   end  
  # end

  def destroy
    @tarif = Tarif.find(params[:id])
      @tarif.destroy
    redirect_to super_admin_tarifs_path, danger:"Taux supprimé"
  end

end

app/helpers/super_admin/actus_helper.rb
module SuperAdmin::ActusHelper
end

app/helpers/super_admin/contacts_helper.rb
module SuperAdmin::ContactsHelper
end

app/helpers/super_admin/projets_helper.rb
module SuperAdmin::ProjetsHelper
end

app/helpers/super_admin/tarifs_helper.rb
module SuperAdmin::TarifsHelper
end

app/helpers/super_admin/update_projets_helper.rb
module SuperAdmin::UpdateProjetsHelper
end

app/helpers/super_admin/users_helper.rb
module SuperAdmin::UsersHelper
end

app/views/super_admin/update_projets/create.html.erb
<h1>SuperAdmin::UpdateProjets#create</h1>
<p>Find me in app/views/super_admin/update_projets/create.html.erb</p>

app/views/super_admin/update_projets/index.html.erb
<div class="container sans-head mb-2">
	<div class="text-center text-muted mt-4 mb-4">
		<h3 class="tablePrint"> Liste des projets modifiés par l'administrateur</h3>
	</div>
	<div class="container mb-5">
		<div class="row">
			<% @projets.each do |p|%>
			<div class="col-md-4 mb-3">
				<div class="card card-height position-relative">
					<div class="card-body">
						<h5 class="card-title"><%= p.nom_du_projet.truncate(40) %></h5>
						<p class="card-text"><%= raw truncate(sanitize(p.objectif_generale_du_projet, tags: []), length: 100)%></p>
						<div class="row align-items-center mt-2 position-absolute card-foot">
							<a href="<%= super_admin_update_projet_path(p.id)%>" class="col tablePrint mb-0">Voir</a>
						</div>	
					</div>
				</div>
			</div>
			<%end%>	
		</div>
		<div class="text-center">
			<%= paginate @projets %>
		</div>
	</div>
</div>

app/views/super_admin/update_projets/show.html.erb
<header class="aci59a-0 eyAIuG sticky-limit">
    <div class="sc-1gnwgfb-2 hVIPFV picc position-relative">
      <style type="text/css">
        .picc{
          <%if @projet.secteurprojets.count == 1%>
            <%@projet.secteurprojets.each do|sp|%>
              <%if sp.secteur.title == "ENERGIE"%>
                background-image: url('/secteur/energie.jpg'); 
              <%else%>
                background-image: url('/<%=sp.secteur.image_url%>');
              <%end%>
            <%end%>
          <%else%>
            background-image: url('/secteur/accueil.jpg');
          <%end%>
        }
      </style>
      <div class="position-absolute entete">
        <h3 class="bg-fiche p-1 text-white"><%=@projet.nom_du_projet%></h3>
      </div>
    </div>
</header>
<div class="objectif mx-auto my-3 row align-items-start">
  <div class="col-12 col-md-2">
    <%if @projet.ptf.image_url%>
      <img src="/<%= @projet.ptf.image_url%>">
    <%end%>
  </div>
  <div class="ml-4 col-12 col-md-9 mt-2">
    <div>
      <div class="">
          <% if  @projet.secteurprojets.count > 0%>
            <%if  @projet.secteurprojets.count == 1%>
                <p><span class="attr">Secteur : </span>
            <%elsif @projet.secteurprojets.count > 1%>
                <p><span class="attr">Secteurs : </span>
            <%end%>
              <span class="word">
                <%@projet.secteurprojets .each do|sp|%>
                    <% if sp == @projet.secteurprojets.last%>
                      <%=sp.secteur.title %>
                    <% else %>
                      <%=sp.secteur.title %>, 
                    <% end %>
                <% end %>
              </span>
            </p>
          <%end%>
          
          <%if @projet.formeprojets.count > 0%>
            <% if @projet.formeprojets.count == 1%>
                <p><span class="attr">Forme d'appui : </span>
            <%elsif @projet.formeprojets.count > 1%>
                <p><span class="attr">Formes d'appui : </span>
            <%end%>
            <span class="word">
                <%@projet.formeprojets .each do|fop|%>
                  <% if fop == @projet.formeprojets.last%>
                    <%=fop.forme.title %>
                  <% else %>
                    <%=fop.forme.title %>, 
                  <% end %>
                <% end %>
              
            </span>
            </p>
          <%end%>

          <%if @projet.filiereprojets.count > 0%>
            <% if  @projet.filiereprojets.count == 1%>
                <p><span class="attr">Filière : </span>
            <%elsif @projet.filiereprojets.count > 1%>
                <p><span class="attr">Filières : </span>
            <%end%>
            <span class="word">
                <%@projet.filiereprojets .each do|fp|%>
                  <% if fp == @projet.filiereprojets.last%>
                    <%=fp.filiere.title %>
                  <% else %>
                    <%=fp.filiere.title %>, 
                  <% end %>
                <% end %>
            </span>
            </p>
          <%end%>
      </div>
    </div>
  </div>
</div>
  <div class="show-cont pt-4 pb-4">
    <div class="objectif mx-auto">
      <h2 class="text-left color">Objectif général du projet</h2>
      <div class="mt-2 ml-3 pt-2">
        <%=  raw @projet.objectif_generale_du_projet%>
      </div>
      <div class="appui mt-4">
        <h2 class="color text-left">Appui spécifique au secteur privé</h2>
        <div class="mt-2 ml-3 p-2">
          <%=  raw @projet.aspsp %>
        </div>
      </div>
      <div class="row pt-4 pb-4">
        <div class="col-md-6 list">


          <% if  @projet.igaprojets.count > 0%>
            <% if  @projet.igaprojets.count == 1%>
                <p><span class="attr">Institution Gouvernementale Associée : </span></p>
            <%elsif @projet.igaprojets.count > 1%>
                <p><span class="attr">Institutions Gouvernementales Associées : </span></p>
            <%end%>
            <div class="mb-3">
                <%@projet.igaprojets.each do|g|%>
                    <%if g == @projet.igaprojets.last%>
                      <span><%=g.iga.title %></span>
                    <% else %>
                      <span><%=g.iga.title %>, </span>
                    <% end %>
                <% end %>
            </div>
          <%end%>

          <% if  @projet.zoneprojets.count > 0%>
            <% if  @projet.zoneprojets.count == 1%>
                <p><span class="attr">Région : </span></p>
            <%elsif @projet.zoneprojets.count > 1%>
                <p><span class="attr">Régions : </span></p>
            <%end%>
            <div class="mb-3">
                <%@projet.zoneprojets .each do|zp|%>
                  <% if zp == @projet.zoneprojets.last%>
                    <%if zp.zone.id == 1%>
                      <span>National</span>
                    <%else%>
                      <span><%=zp.zone.title %></span>
                    <%end%>
                  <%else%>
                    <%if zp.zone.id == 1%>
                      <span>National, </span>
                    <%else%>
                      <span><%=zp.zone.title %>, </span>
                    <%end%>
                  <% end %>
                <% end %>
            </div>
          <%end%>


          <% if  @projet.benefprojets.count > 0%>
            <% if  @projet.benefprojets.count == 1%>
                <p><span class="attr">Bénéficiaire : </span></p>
            <%elsif @projet.benefprojets.count > 1%>
                <p><span class="attr">Bénéficiaires : </span></p>
            <%end%>
            <div class="mb-3">
                <%@projet.benefprojets .each do|ben|%>
                    <%if ben == @projet.benefprojets.last%>
                      <span><%=ben.beneficiaire.title %></span>
                    <% else %>
                      <span><%=ben.beneficiaire.title %>, </span>
                    <% end %>
                <% end %>
            </div>
          <%end%>

          <% if  @projet.secteurprojets.count > 0%>
          <%if  @projet.secteurprojets.count == 1%>
              <p><span class="attr">Montant  pour le secteur : </span>
          <%elsif @projet.secteurprojets.count > 1%>
              <p><span class="attr">Montant  pour les secteurs : </span>
          <%end%>
          </p>
          <div class="row">
            <% @projet.montants.each do |m|%>
                  <div class="col-12 col-md-7">
                    <span><%= m.secteur.title.titleize%> : </span>
                  </div>
                  <div class="col-12 col-md-5">
                    <span><%=  number_with_delimiter(m.price) %> <%= m.unite.nom%></span> 
                  </div>
            <%end%>
          </div>
          <%end%><br>
          <div class="row">
                  <div class="col-12 col-md-7">
                    <span class="attr">Montant total :</span>
                  </div>
                  <div class="col-12 col-md-5">
                    <span><%= number_with_delimiter(@montant_total)%> USD</span> 
                  </div>
          </div>
        </div>
        <div class="col-md-6 list">
          <p class="mb-3"><span class="attr">Nature de l'appui : </span><%=@projet.appui.title%></p>
          <%if @projet.debut_du_projet && @projet.fin%>
            <p class="mb-3"><span class="attr">Début de projet : </span><%=@projet.debut_du_projet.year%> &nbsp;&nbsp;&nbsp;&nbsp;
            <span class="attr">Fin de projet : </span><%=@projet.fin.year%></p>
          <%end%>
          <%if @projet.pemprojets.count >= 1%>
          <p><span class="attr">Alignement aux priorités du Plan Emergence Madagascar : </span></p>
            <div class="mb-3">
              <% @projet.pemprojets.each do |p|%>
                  <p><%=p.pem.title%></p>
              <%end%>
            </div>
          <%end%>
       
        </div>
    </div>
    <div class="text-right">
     <a href="<%= edit_super_admin_update_projet_path(@projet.id)%>" data-method="get" class="sc-eerKOB cfnPHQ bold sear">Modifier</a>
      <a href="<%= super_admin_projet_path(@projet.projet_id)%>" class="btn btn-primary">Voir la version initiale</a>
      <a href="<%= super_admin_update_projet_path(@projet.id)%>" class="btn btn-danger" data-method="delete" data-confirm="Voulez-vous supprimer ce projet modifié ?"> Supprimer</a>
     <a href="<%= super_admin_projets_path%>" class="btn btn-secondary">Retour</a>
    </div>

<%= render partial: "/super_admin/confirm.html.erb"%>

app/views/super_admin/update_projets/update.html.erb
<h1>SuperAdmin::UpdateProjets#update</h1>
<p>Find me in app/views/super_admin/update_projets/update.html.erb</p>