config/routes.rb
Rails.application.routes.draw do
 
    resources :actus
    resources :apropos
    resources :contacts
    resources :publications

    	namespace :admin do
	  	resources :projets
	  	resources :users
      resources :publications

    end
 # 	resources :secteur
 # 	resources :pft
 #  resources :filiere

 	  namespace :super_admin do
      resources :publications
	    resources :users 
	    resources :projets
      resources :actus
      resources :tarifs
      resources :contacts
      resources :update_projets
  	end
    
   root to: 'home#index'
   devise_for :users, :controllers => { :sessions => "sessions" }
   get 'users/index'
   resources :projets
   get '/search' => 'projets#search', :as => 'search_projet'

   # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/actu.rb
class Actu < ApplicationRecord

	has_many_attached :files
	belongs_to :user
end

app/controllers/actus_controller.rb
class ActusController < ApplicationController
   before_action :authenticate_user!
   before_action :check_if_account_validate

  def index
  	@actus = Actu.all.order(date_publication: :desc).page(params[:page]).per(9)
  end

  def new
  end

  def show
    @actu = Actu.find(params[:id])
  end
  
  def update
  end

  private
  def check_if_account_validate
      if current_user.is_consultant == false && current_user.is_admin == nil && current_user.is_super_admin == false
        redirect_to root_path, success: "Compte en attente de validation, vous ne pouvez pas consulter toutes les actualités"
      end
  end
end

app/controllers/super_admin/actus_controller.rb
class SuperAdmin::ActusController < ApplicationController
  before_action :authenticate_user!

  def create
      @actu = Actu.create!(title: params[:title], date_publication: params[:date_publication], user_id: current_user.id)

      if @actu.save
       @actu.files.attach(params[:files])
       redirect_to new_super_admin_actu_path, success: "Actualité créée avec succès"
     else
       render :new

     end 


  end

  def new

    @actus = Actu.where(user_id: current_user.id).order(date_publication: :desc).page(params[:page]).per(9)
    @actu = Actu.new
  end

  def index
    @actus = Actu.where(user_id: current_user.id).order(date_publication: :desc).page(params[:page]).per(9)
  end

  def show
    @actu = Actu.find(params[:id])
  end

  def edit
    @actu = Actu.find(params[:id])
    @actus = Actu.where(user_id: current_user.id).order(date_publication: :desc).page(params[:page]).per(9)
  end

  def update
      @actu = Actu.find(params[:id])
      if params[:files] != nil
        if @actu.update(title: params[:title],files: params[:files], user_id: current_user.id)
         redirect_to super_admin_actu_path, succès: "Modification terminée"
        end
      else
        if @actu.update(title: params[:title], user_id: current_user.id)
         redirect_to super_admin_actu_path, succès: "Modification terminée"
        end
      end
  end

  def destroy
    @actu = Actu.find(params[:id])
    @actu.destroy
    redirect_to super_admin_actus_path
  end

end

app/helpers/actus_helper.rb
module ActusHelper
end

app/helpers/super_admin/actus_helper.rb
module SuperAdmin::ActusHelper
end

app/views/actus/index.html.erb
<div class="container sans-head mb-5">
	<%if @actus.count == 0 %>
			<div class="text-center text-muted mt-1 mb-4">
				<p> Aucune actualité</p>
			</div>
		<%else%>
	<div class="mb-4 text-center">
		<h3 class="tablePrint">Toutes les actualités</h3>
	</div>
	<div class="row justify-content-center">
		<% @actus.each do |a|%>
			<div class="col-md-3 mb-2 card mx-1 position-relative">
				<div class="card-body">
			 	 	<div class="card-title tablePrint">
				    	<h6><%= a.date_publication%></h6>
				    </div>
					<div class="card-text">
						<p class="card-text text-muted mb-5 truncate-pub"><%= a.title %></p>
					</div>
				    <p class="mt-3 position-absolute more-info-pub"><a href="<%= actu_path(a.id)%>" class="tablePrint">Voir</a></p>
				</div>
			</div>
		<%end%>	
	</div>
	<div class="text-center">
		<%= paginate @actus %>
	</div>
<%end%>
</div>

app/views/actus/show.html.erb
<div class="container sans-head" >
	<div class="titre">
		<h6 class="text-muted mt-3 mb-3 text-justify"><%=@actu.title%></h6>
    </div>
   <div>
		<div class="mt-3">
			<%if @actu.files.attached?%>
				<p>Liste des documents associés :</p>
				<ol class="ml-4">
					<%@actu.files.all.each do|file|%> 
						<li class="mb-3 mt-3"><%= link_to file.filename, rails_blob_path(file, disposition: "attachement"), class: "doc-relative ml-2 text-break text-wrap" , target: :_blank%></li>
					<%end%>
				</ol>
			<%end%>
		</div>
	</div>
</div>